services:
  directus:
    image: directus/directus:latest
    ports:
      - "8055:8055"
    volumes:
      - ./directus/database:/directus/database
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'
      DB_CLIENT: 'sqlite3'
      DB_FILENAME: '/directus/database/data.db'
      ADMIN_EMAIL: 'alper.tombulca@web.de'
      ADMIN_PASSWORD: 'CarBot2024!'
      PUBLIC_URL: 'http://localhost:8055'
      CORS_ENABLED: 'true'
      CORS_ORIGIN: 'http://localhost:3000,http://localhost:8055'
    restart: unless-stopped