name: ✨ Feature Request
description: Suggest a new feature or enhancement for CarBot
title: "[FEATURE] "
labels: ["type:feature", "priority:P3"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible to help us understand and prioritize your request.

  - type: dropdown
    id: feature_type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Feature (Completely new functionality)
        - Enhancement (Improvement to existing feature)
        - Integration (Third-party service integration)
        - Performance (Speed/efficiency improvement)
        - UI/UX (User interface improvement)
        - Security (Security enhancement)
        - Compliance (Regulatory/compliance feature)
        - Localization (Language/region support)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Business Priority
      description: How important is this feature for business operations?
      options:
        - P3 - Nice to have (Future consideration)
        - P2 - Important (Should be planned)
        - P1 - High (Business impact)
        - P0 - Critical (Essential for operations)
      default: 0
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component Area
      description: Which part of the system would this feature affect?
      options:
        - Authentication & User Management
        - Workshop Management
        - Customer Communication
        - Dashboard & Analytics
        - Payment & Billing
        - Email System
        - Mobile App
        - API & Integrations
        - Admin Tools
        - Reporting
        - Security
        - Performance
        - German Market Specific
        - Other
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: Brief, clear description of the feature
      placeholder: In one or two sentences, describe what this feature would do
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Describe the current challenge or limitation that this feature would address:
        - What is the current pain point?
        - Who is affected by this problem?
        - How often does this problem occur?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Detailed description of the feature
      placeholder: |
        Describe your proposed solution in detail:
        - How should this feature work?
        - What should the user experience be?
        - Any specific requirements or constraints?
    validations:
      required: true

  - type: textarea
    id: use_cases
    attributes:
      label: Use Cases
      description: Specific scenarios where this feature would be used
      placeholder: |
        Provide specific examples of how this feature would be used:
        1. User scenario 1...
        2. User scenario 2...
        3. Admin scenario...
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: What conditions must be met for this feature to be considered complete?
      placeholder: |
        Define clear criteria for completion:
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: checkboxes
    id: business_impact
    attributes:
      label: Business Impact
      description: How would this feature impact the business?
      options:
        - label: Increases customer acquisition
        - label: Improves customer retention
        - label: Reduces operational costs
        - label: Increases revenue potential
        - label: Improves team efficiency
        - label: Reduces support burden
        - label: Enhances competitive advantage
        - label: Addresses compliance requirements

  - type: checkboxes
    id: german_market
    attributes:
      label: German Market Considerations
      description: Is this feature relevant to the German market?
      options:
        - label: Required for German legal compliance
        - label: GDPR/DSGVO specific requirement
        - label: German language support needed
        - label: German payment method integration
        - label: German automotive industry specific
        - label: Cultural/regional customization

  - type: dropdown
    id: user_type
    attributes:
      label: Target Users
      description: Who would primarily use this feature?
      options:
        - Workshop Owners
        - Workshop Employees
        - End Customers
        - System Administrators
        - Support Team
        - All Users
        - Specific Role (describe in additional context)
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered other ways to solve this problem?
      placeholder: |
        Describe any alternative approaches you've considered:
        - Alternative solution 1...
        - Alternative solution 2...
        - Why the proposed solution is preferred...

  - type: textarea
    id: technical_considerations
    attributes:
      label: Technical Considerations
      description: Any technical requirements or constraints to consider?
      placeholder: |
        Consider technical aspects:
        - Performance requirements
        - Security considerations
        - Integration needs
        - Scalability requirements
        - Browser/device compatibility

  - type: input
    id: timeline
    attributes:
      label: Desired Timeline
      description: When would you like to see this feature implemented?
      placeholder: e.g., Next quarter, Before summer, No specific timeline

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/References
      description: Any visual mockups, wireframes, or reference examples
      placeholder: |
        Attach or describe any visual references:
        - Screenshots from other apps
        - Hand-drawn sketches
        - Links to similar features
        - Detailed workflow diagrams

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: |
        Include any other helpful information:
        - Related features or integrations
        - Customer feedback
        - Market research
        - Competition analysis

  - type: markdown
    attributes:
      value: |
        ---
        **Feature Request Process:**
        1. **Initial Review** - Product team reviews and labels the request
        2. **Requirements Analysis** - Detailed technical analysis if approved
        3. **Design Phase** - UI/UX design and technical specification
        4. **Development** - Implementation with testing
        5. **Release** - Feature deployment and user communication
        
        **German Market Priority:** Features supporting German market expansion receive higher priority consideration.